質問箱一覧ページを作成する
fjordllc/tallk pull request #10
Opened 2020-10-07 14:20 UTC by KishiKyousuke

2020-10-07 16:02 UTC, KishiKyousuke commented
@machida 
このような実装でよろしかったでしょうか❓
こちらのデザインをよろしくお願いいたします🙇🏻‍♂️

2020-11-05 03:56 UTC, machida commented
@KishiKyousuke デザイン入れましたー
@komagata レビューをお願いします。ファイルが多いのですが、ほとんどが管理画面のテンプレートのためのsassファイルになります。

2020-11-06 02:29 UTC, komagata commented on app/controllers/rooms_controller.rb
> +    render layout: 'admin'
bootcampみたいにAdminControllerを作ってそれを継承する形がいいかもです。

2020-11-06 03:34 UTC, KishiKyousuke commented
@komagata 
admin_controllerを作成し、これを継承したrooms_controllerを新たに作成しました。
レビューをお願いいたします🙇🏻‍♂️

2020-11-06 07:28 UTC, komagata requested changes

2020-11-06 07:28 UTC, komagata commented on app/controllers/admin_controller.rb
> +class AdminController < ApplicationController
何もないと継承する意味がないので、layoutの処理をこちらに書きたいという感じです。　

2020-11-06 07:50 UTC, KishiKyousuke commented
@komagata 
layoutの指定を`admin_controller.rb`で行うように変更いたしました❗
ご確認をよろしくお願いいたします🙇🏻‍♂️

2020-11-08 06:10 UTC, komagata requested changes

2020-11-08 06:10 UTC, komagata commented on app/controllers/rooms_controller.rb
> +    render layout: 'admin'
ここはどうなっていますか？

2020-11-08 06:29 UTC, KishiKyousuke commented on app/controllers/rooms_controller.rb
> +    render layout: 'admin'
@komagata 
申し訳ありません💦
削除するのをを忘れていました😓

2020-11-08 07:02 UTC, KishiKyousuke commented
@komagata 
`app/controllers/rooms_controller.rb`内に残っていたindexアクションを削除しました。

2020-11-15 12:49 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-11-15 12:49 UTC, merged

2020-11-18 06:04 UTC, KishiKyousuke commented
現状、質問箱一覧画面を誰でも見られる状態になっているので、別PRで認証機能を実装します。

2020-11-18 08:53 UTC, KishiKyousuke commented
@komagata 
認証機能の実装に関してですが、フィヨルドトークにはログイン機能がないため管理者登録用の`admin_user`というようなモデルを新たに作成し、`admin/rooms`にアクセスする際にBasic認証を行うという実装を考えています。
その場合、管理者ユーザーの登録はコンソール上でのみ行えるようにするという認識で大丈夫でしょうか❓

2020-11-22 10:44 UTC, komagata commented
@KishiKyousuke Basic認証を使う場合はそれ用のユーザーモデルは必要ないと思います。