質問箱を作成する際にパスワードを設定できるようにする
fjordllc/tallk pull request #14
Opened 2020-10-29 02:38 UTC by KishiKyousuke

ref #5 

## 概要
- 質問箱作成画面にパスワードの入力フォームを追加しました
- パスワードは4文字以上に制限しました
- パスワードが4文字未満の場合やパスワードと確認用パスワードが一致しないときにフォームを送信しようとするとHTMLから警告が出るように実装しました

2020-10-29 02:43 UTC, KishiKyousuke commented
@machida 
デザインのご確認をお願いいたします🙇🏻‍♂️

2020-10-29 03:05 UTC, KishiKyousuke commented
@machida 
デザインのご確認をよろしくお願いいたします🙇🏻‍♂️

2020-11-05 08:39 UTC, machida commented
@KishiKyousuke 

ちょっと検討をしたのですが、UIを変更したいと思います。

変更箇所なのなのですが、room作成、編集の

- パスワードを入力中、した後も見れるようにして欲しい（type="text"）で行けるかと思います。
- パスワードの入力は一回だけにして欲しい

この二箇所になります。

ライトなツールであることを伝えたく、パスワード忘れを防ぐことよりも、入力回数の少なさを優先させたく、このようにお願いします🙏

2020-11-05 08:40 UTC, machida commented
デザインは入れたのでpushしますー
roomsを入れたPRをrebaseしました。なので、一旦このブランチを git pull --rebase origin password-can-be-set-in-question-box をお願いしますー

2020-11-06 02:19 UTC, KishiKyousuke commented
@komagata 
レビューをお願いいたします❗

2020-11-06 07:20 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2020-11-06 07:20 UTC, komagata commented on app/models/room.rb
> +  validates :password, presence: true, length: { minimum: 4 }
👍

2020-11-06 07:21 UTC, komagata commented
完了していたらDraftを外して提出状態にしてください〜

2020-11-06 07:33 UTC, KishiKyousuke commented
@komagata 
こちらのPRはまだ未修正の段階の #10 のコミットをrebaseしているのですが、一旦こちらをmergeしたあとに #10 の修正後のPRをmergeするという流れでよろしいでしょうか❓

2020-11-08 06:14 UTC, komagata commented
@KishiKyousuke 

> #10 のコミットをrebaseしているのですが

ってどういう意味でしょうか？

このブランチがadd-room-list-pageの内容をもとにしているとするとadd-room-list-pageがmasterにmergeされた後、今いるブランチをmasterにrebaseしてから完成させる必要があります。

もしくはこのPRの向き先をmasterではなくadd-room-list-page向きにするなどです。

2020-11-08 06:57 UTC, KishiKyousuke commented
@komagata 
以下の@machidaさんのコメントにあるように、このブランチはデザインを入れていただく段階でadd-room-list-pageをrebaseしているので、add-room-list-pageの内容を元にしていると言えると思います。
現在のadd-room-list-pageの内容はこのブランチにrebaseしてきたときの内容から変更されているため、このブランチにはadd-room-list-pageの古い内容が残されている状態となっています。

![image](https://user-images.githubusercontent.com/59789739/98458875-75ec3900-21d8-11eb-9e18-f2a8fb158fae.png)

2020-11-09 07:38 UTC, komagata commented
@KishiKyousuke なるほどですね。こちらがマージされたら #10 をマージするで良いと思います。

2020-11-09 09:45 UTC, machida commented
@KishiKyousuke これを、masterにマージしてしまうと、管理画面がないのにパスワード入力だけがある状態がリリースされてしまうので、このブランチをフィーチャーブランチとして、管理画面系のPRをこのブランチに向けて、管理画面系の機能が揃ったらマスターにマージでいきたいと思いますー

2020-11-09 09:56 UTC, KishiKyousuke commented
@komagata @machida
となると、先に #10 をマージするということになりますか❓
その場合、 #10 をマージしたmasterをこのブランチにrebaseして、add-room-list-pageの古い内容を更新するというようなことは可能でしょうか❓

2020-11-09 22:19 UTC, machida commented
@KishiKyousuke 

はい、先に #10 をmasterにマージして、#10 は先にリリースしてしまいますー
#10 をマージしたmasterをこのブランチにrebaseすれば、add-room-list-pageの古い内容も更新されるはずです。

もし、上手く行かなかった場合は、新たにmasterからブランチを作って、このPRに積まれてるcommitを新しいブランチにcherry-pickしましょう。

2020-11-10 05:24 UTC, komagata commented
@KishiKyousuke すみません、Issueの依存関係がわかっていませんでした。@machida さんのおっしゃる通りで大丈夫です。

2020-11-18 06:02 UTC, KishiKyousuke commented
既存の質問箱にパスワードを設定するRakeタスクを追加します。

2020-11-22 05:40 UTC, komagata requested changes

2020-11-22 05:40 UTC, komagata commented on app/views/topics/new.html.slim
> +javascript:
@KishiKyousuke こちら @machidaさんが追加された箇所だとは思いますが、`app/javascript`以下のwebpackerでコンパイルされて動くように修正お願いしたいです〜

2020-12-04 04:33 UTC, KishiKyousuke commented
@komagata 
JSのコードの移動、およびRakeタスクの作成を行いました。
`app/javascript`下のディレクトリ構成や、Rakeタスクの名前空間に関しては暫定的なものなのでアドバイスを頂けると幸いです❗
ご確認よろしくお願いいたします🙇🏻‍♂️

2020-12-07 01:47 UTC, komagata requested changes

2020-12-07 01:47 UTC, komagata commented on app/javascript/packs/application.js
> +/* eslint no-console:0 */
`app/javascript/packs`以下に置くのはpackされてる（1ファイルにまとめられて使われるJS）ものだけなのでこのぐらいの規模のサイトではapplication.jsだけで大丈夫です。

webpackは利用するJSファイルを最終的に1ファイルにまとめることでキャッシュさせて読み込みを早くするために使われます。

bootcampのソースコードを参考にしてみてください〜

2020-12-09 01:49 UTC, KishiKyousuke commented
@komagata 
エントリポイントを`application.js`に統一し、JSのコードを`app/javascript`下に移動させました！
ご確認よろしくお願いいたします！

2020-12-09 06:45 UTC, komagata requested changes

2020-12-09 06:45 UTC, komagata commented on app/javascript/packs/application.js
> +require('../rooms.js')
bootcampもこうなっているので変えなきゃなんですが、importの方がいいと思います。

2020-12-09 06:45 UTC, komagata commented on app/javascript/rooms.js
> +document.addEventListener('DOMContentLoaded', () => {
なんの処理をしているのかという観点の名前にした方がいいと思います。

2020-12-10 01:55 UTC, KishiKyousuke commented
@komagata 
JSファイルを、formの処理・noticeの処理・slideの処理に分割しました！
ご確認よろしくお願いいたします。

2020-12-10 01:56 UTC, KishiKyousuke commented on app/views/rooms/show.html.slim
> +            = link_to 'トーク開始！', room_topics_path(@room), class: 'a-ex-button is-danger'
@machida 
こちらのトーク開始ボタンはコメントアウトしたままでよろしかったでしょうか❓

2021-01-13 05:02 UTC, machida commented on app/views/rooms/show.html.slim
> +            = link_to 'トーク開始！', room_topics_path(@room), class: 'a-ex-button is-danger'
@KishiKyousuke すいません、このメッセージを見逃してました🙇‍♂️ はい！トーク開始はパスワードでログインした先で表示したいと思いますー

2021-01-13 06:07 UTC, komagata requested changes

2021-01-13 06:07 UTC, komagata commented on app/javascript/form.js
> +  const input = document.getElementById('room_name') || document.getElementById('topic_who');
form.jsという名前は全てのformに対して動くという意味合いがあると思うので、何かの個別のformに関する処理は別ファイル（その機能の名前を付けたファイル名）にした方がいいと思います。

2021-01-18 00:31 UTC, KishiKyousuke commented
@komagata 
これまで`form.js`に集約していたフォームに関する処理を、`room_form.js`と`topic_form.js`に分割しました。
ご確認よろしくお願いいたします。

2021-01-18 02:09 UTC, komagata requested changes

2021-01-18 02:09 UTC, komagata commented on app/javascript/packs/application.js
> +
不要な空行があるようです〜

2021-01-18 02:09 UTC, komagata commented on app/javascript/room_form.js
> +document.addEventListener('turbolinks:load', () => {
ファイル名は対象の名前よりも何をやってるのかという観点でつけた方がいいと思います。そしてそれは他のformも共通にできたりしないですかね？

2021-01-18 04:57 UTC, KishiKyousuke commented
@komagata 
以下の点を修正いたしました。

- 不要な空行の削除
- `topic_form.js`と`room_form.js`を`check_required_input.js`に統一

必須項目としてチェックしたいinput要素に`js-required-input1`と`js-required-input2`というIDを与えることで、その項目に値が入力されている状態のときだけ、submitボタンを押せるようにしています。
ご確認よろしくお願いいたします。

2021-01-20 05:49 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-01-20 05:49 UTC, merged