質問箱管理画面の追加
fjordllc/tallk pull request #16
Opened 2020-12-10 04:32 UTC by KishiKyousuke

ref #11 

## 目的
質問箱作成の際に設定したパスワードを使用して、投稿された質問一覧を確認できる質問箱管理画面にアクセスできるようにする。

## 変更点
- `admin/rooms_controller.rb`にshowアクションを追加
- showアクションに固有の認証を追加
- 質問箱管理画面`admin/rooms/show.html.slim`を作成
- 質問箱トップページ`rooms/show.html.slim`に質問箱管理画面へのリンクとパスワード入力フォームを追加

2020-12-10 04:35 UTC, KishiKyousuke commented
@machida 
`rooms/show.html.slim`に追加した質問箱管理画面へのリンクとパスワード入力フォームのデザインをお願いいたします！
加えて、質問箱管理画面`admin/rooms/show.html.slim`は質問箱一覧画面のデザインを流用しているため、こちらのデザインのご確認もよろしくお願いいたします！

2021-01-18 00:13 UTC, KishiKyousuke commented
@MashioSano 
もしお時間がよろしければレビューをお願いいたします❗
フォームの位置等のデザインは町田さんに調整していただく予定です。

2021-01-19 05:45 UTC, MashioSano requested changes
お待たせしました~
一点気になる点をコメントしました。
ご確認のほどよろしくお願いします!

2021-01-19 05:45 UTC, MashioSano commented on app/controllers/admin/rooms_controller.rb
> +    @topics = Room.page(params[:page])
<code>@rooms</code>から<code>@topics</code>に変更した理由が気になりました！👀

2021-01-19 05:59 UTC, KishiKyousuke commented on app/controllers/admin/rooms_controller.rb
> +    @topics = Room.page(params[:page])
@MashioSano 
ご指摘ありがとうございます！
完全な凡ミスを見逃してました！助かります😄

2021-01-19 06:09 UTC, KishiKyousuke commented on app/controllers/admin/rooms_controller.rb
> +    @topics = Room.page(params[:page])
@MashioSano 
ご指摘いただいた箇所を修正しました！
お手すきの際にご確認よろしくお願いいたします！😊

2021-01-19 08:39 UTC, MashioSano approved these changes
確認しました!LGTMです!🎊

2021-01-19 08:49 UTC, MashioSano commented
@KishiKyousuke 
このプルリクエストのFile Changedの範囲外になりますが、ここの<code>password_confirmation</code>はなくても動くと思いました!
https://github.com/fjordllc/tallk/blob/af55a6f1b58bc4a55ce74fd711b02001c14545ef/app/controllers/rooms_controller.rb#L37-L40
(既に手元でこの部分を修正されていたらすいません)

2021-01-19 09:11 UTC, KishiKyousuke commented
@MashioSano 
こちらもご指摘ありがとうございます❗
派生元のブランチに修正を加えておきました😊

2021-01-19 09:11 UTC, KishiKyousuke commented
@komagata 
お手すきの際に、レビューをお願いいたします❗🙇🏻‍♂️

2021-01-20 05:40 UTC, KishiKyousuke commented
@komagata 
質問箱管理画面の「作成時間」の表示をlメソッドを使用した形式に修正しました。
また、以前マージされた #10 のPRで作成したviewにもlメソッドを使用せず時間表示をしている箇所があったため、Issueを作成しておきます。
お手すきの際にレビューをお願いいたします🙇🏻‍♂️

2021-01-20 06:09 UTC, komagata requested changes

2021-01-20 06:09 UTC, komagata commented on config/locales/ja.yml
> +      default: "%Y/%m/%d %H:%M"
`rails-i18n` gemとかにはこういうの含まれているのでそれを使うといいかもです。

2021-01-20 06:10 UTC, komagata commented
@KishiKyousuke レビュー依頼するときはDraftじゃない状態でお願いします〜（未完成でレビュー依頼という意味合いになるので）

2021-01-20 07:51 UTC, KishiKyousuke commented
@komagata 
rails-i18nを導入し、時間の表示形式をrails-i18n内に定義されたフォーマットを使うように変更しました。
町田さんにデザインを依頼している状態なので、DraftPullRequestのままでレビューを依頼してしまいました💦

2021-01-22 09:11 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2025-05-04 20:04 UTC, closed without merging